### ISSUE TITLE
USB-UART bitstream difference

### ISSUE THREAD

**Issue by ltarjanyi** [Noltari/pico-uart-bridge#13]
Hello!

I'm trying to use your bridge to connect to a fingerprint sensor with it's windows based demo application (SFGDemo) created to demonstrate it's features.

The sensor works fine with Adafruit library and its examples created for Arduino. But the windows app cannot connect it with the proposed method described here: https://learn.adafruit.com/adafruit-optical-fingerprint-sensor/enrolling-new-users-with-windows. I assume that it does not work, because I have a clone Arduino uno. Also tried to use Arduino as an USB-serial converter by connecting RESET pin to GND proposed somewhere else. Looking with scope on TX pin I see the communication, but the signal does not go to GND when the signal is low, just to around 2 Volts.

Trying the same with PICO and your bridge I experience that after a few bytes the I do not read the same bytes that is sent by the windows app. For this fingerprint sensor the first two bites are always 0xEF, 0x01 followed by the fingerprint sensor default address (0xFFFFFFFF). When I look at the TX signal with scope the first 4 bytes are always correct but after that it is differs. I can see EF 01 FF FF 00 00 ... instead of EF 01 FF FF FF FF ... and so the app cannot connect to the specific COM port.
Sometimes the 3rd byte of the address is also correct, but never seen the 4th address byte to be correct.

Tried to play with bitrate, but it did not help. Do you have any idea what could be the problem or what I should check?

 Thanks for your help.

**Comment by Noltari** [comment]
Fixed by https://github.com/Noltari/pico-uart-bridge/pull/15
