### ISSUE TITLE
Broken on Nano RP2040 Connect 

### ISSUE THREAD

**Issue by retu2libc** [Noltari/pico-uart-bridge#18]
Some commit between [2021](https://forums.raspberrypi.com/viewtopic.php?t=302684#p1813886) and now broke pico-uart-bridge on the nano rp2040. Mine has AT25SF041 flash. The `/dev/ttyACMX` devices don't appear anymore. It seems to be getting recognized as a usb mass storage (from dmesg):
```
usb-storage 1-1:1.0: USB Mass Storage device detected
```
The most recent tagged version I can find working is  [2.1](https://github.com/Noltari/pico-uart-bridge/releases/tag/v2.1)

**Comment by Noltari** [comment]
Fixed by https://github.com/Noltari/pico-uart-bridge/commit/b74af3b0d8aa27cb01193f1283394112809b2815
