### ISSUE TITLE
A serial port 1

### ISSUE THREAD

**Issue by H-sw123** [Noltari/pico-uart-bridge#3]
How can I make both serial ports work?I found that only one serial port works and the other one doesn't work.

**Comment by Noltari** [comment]
Both serial ports should work.
I tested that and it worked. Are you sure you connected it correctly?

**Comment by nikisalli** [comment]
I tested it today, both master and next branches and while serial port 0 works like a charm, serial port 1 only works for writing, it spits tons of garbage when being read with cat on linux

**Comment by Noltari** [comment]
I tested this again with the latest release (https://github.com/Noltari/pico-uart-bridge/releases/tag/v4.0) without issues.
