### ISSUE TITLE
Full Duplex doesn't work?

### ISSUE THREAD

**Issue by pacsui** [Noltari/pico-uart-bridge#5]
I'm trying to ssh through the first UART bridge to a raspberry pi zero and it only shows the output and doesn't seem to accept any keystrokes.

**Comment by Noltari** [comment]
Could try this commit on the next branch? https://github.com/Noltari/pico-uart-bridge/commit/2460b10523aa3b8537f16f2689c2c051c6de720f
This is the binary generated from the next branch: [pico-uart-bridge.uf2.zip](https://github.com/Noltari/pico-uart-bridge/files/7412210/pico-uart-bridge.uf2.zip)

**Comment by pacsui** [comment]
it doesn't seem to work either :(

**Comment by DatanoiseTV** [comment]
I can confirm that trying to program an ESP32 via the pico-uart-bridge is failing. Is there any solution yet?

**Comment by Noltari** [comment]
Hi, I tried programming an ESP32 with latest release (https://github.com/Noltari/pico-uart-bridge/releases/tag/v4.0), but I couldn't get it detected and flashed with ESPHome.
I'm using pico-uart-bridge for debugging OpenWrt devices and I don't plan to look into this any further.
However, if anyone wants to investigate this and eventually gets it working I will be happy to merge it via Pull Request.
