### ISSUE TITLE
DTR and RTS

### ISSUE THREAD

**Issue by muebau** [Noltari/pico-uart-bridge#7]
Hello,
do you see a simple way to provide DTR and/or RTS.

There are projects which could use a DTR.
One example could be Chinese diesel heaters or programmer adapters for VHF radios.

They have in common that they use a trick to multiplex RX/TX on one line with the DTR line and 2 transistors.

If the RPi pico would simulate this behavior and would switch TX to high impedance if DTR is set this would become the perfect programming adapter as no additional hardware would be needed.

DTR and RTS could be useful anyway if 2 GPIOs would be used.

**Comment by Noltari** [comment]
This has been implemented by @narvalotech in https://github.com/Noltari/pico-uart-bridge/pull/6
Hopefully I will be able to merge it at any time xD.
